version: "3"

services:


  postgres:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=testdb
        - CONFIGS="listen_addresses:'*'"
      volumes:
        - postgres-db:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    depends_on:
      - postgres

    command: sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000 && alembic upgrade head"
    volumes:
      - .:/code:ro
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - database_hostname=postgres
      - database_port=5432
      - database_password=123456
      - database_name=testdb
      - database_username=postgres

volumes:
  postgres-db:
